### PR TITLE
(bugfix) Finish removal of ffmpeg deprecated API calls.

### PR DESCRIPTION
**Pull request by fsbruva**
This finishes some work to avoid minor compilation warnings (no functional change).

### CODE REVIEW

**Comment by chincheta0815** [comment]
Thanks for the patch. I ran in such a problem already.
Playing with options on how to best make the show compile I reworked the Makefile.PL of libmediascan (not yet pushed) and made the buildme.sh a little bit more ordered in terms of what does the script dor for which OS. I also added the options for custom PERL_LDDLFLAGS etc when needed. What do you think? (https://github.com/chincheta0815/slimserver-vendor/tree/buildme)

**Comment by fsbruva** [comment]
I tried to do somethings similar... https://github.com/Logitech/slimserver-vendor/pull/38

Michael didn't want the changes, if they didn't solve a problem.

**Comment by fsbruva** [comment]
I am working on getting the Osx build working. See my devel /7.9 branch for the latest.

**Comment by chincheta0815** [comment]
Well, as far as I see the changes solve problems also yours with respect to the grown code base and evolution in perl version... Maybe not the obvious ones.
1. Code simplicity:  There are numerous hard coded perl binaries in the code. Maybe one if statement with a short regexp could give some simplicity using just one "custom perl bin" that can be either found by PATH where it usually resides or by command line arg. This is not yet done, might be an idea for the future.
2. Code simplicity: Settings of OS specific Flags etc. All of the perl modules work almost perfectly with standard linux (maybe Ubuntu?). The BSDs, Solaris/Illumos also work, but one has to change some settings. It's the modules breaking the build not the OS as many usually state. Some modules overwrite things, others add LDFLAGS that are incompatible. Speaking for Illumos: XML::Parser builds XML::Parser::Expat. The latter does not get the LDFLAGS properly. Perl of Illumos uses ld not gcc. You can easily change the LDDLFLAGS, but something add's a -m64 to the FLAGS and there is the crash. Changing the FLAGS globally at one place solves a lot of problems there when trying to debug. I think simply adding and ordering the flags setting etc does not break anything but allows for better compatiblity for future purposes.

Another thing I thought about in that context: Make buildme.sh simple and versatile and use it for travis-ci. All I did figure out is that there are CIs for Windows and Linux. I did not figure out one for RasPi and Illumos... This could ease development for example in our case: I do changes for Illumos you for Linux etc... 

What is you opinion? You seem to be better in all that coding stuff.

**Pull request merged**
