### PR TITLE
Create option to omit linking against -lintl

### PR DESCRIPTION
**Pull request by fsbruva**
FreeBSD doesn't contain the GNU gettext stuff, and the comments in the Makefile show that linking to -lintl is only needed for exif logging. This adds an option for FreeBSD or other systems to avoid attempts to link to -lintl. Especially because we don't force it in the exif build within slimserver-vendor. Leaving the option unset preserves the existing link behavior (attempt to link).

### CODE REVIEW

**Comment by chincheta0815** [comment]
Cool idea. That make me think of my "special" LD and LDDLFLAGS at the end of the Makefile.PL concerning sunos|solaris.

What do you think: Leave it as is for "automatic" setting of the correct values or make it a thing for the user?

I personally like it automatic, but my solution does not seem elegant...

**Comment by fsbruva** [comment]
I think you can have the best of both worlds. I'd say leave the "special" LD and LDDFLAGS as defaults, and then let's figure out how people can override them, if necessary. Can you pass them as the commandline to Perl?

That's why I added the extra option - "automatic" seems to work for 99% of people, but I needed more control for the FreeBSD builds. This is how it will get used in slimserver-vendor:

buildme.sh, line 1062:
 ```
 MSOPTS="--with-static \
                --with-ffmpeg-includes=$BUILD/include \
                --with-lms-includes=$BUILD/include \
                --with-exif-includes=$BUILD/include \
                --with-jpeg-includes=$BUILD/include \
                --with-png-includes=$BUILD/include \
                --with-gif-includes=$BUILD/include \
                --with-bdb-includes=$BUILD/include"

if [ "$OS" = "FreeBSD" ]; then
    MSOPTS="$MSOPTS --omit-intl"
fi
```

**Comment by fsbruva** [comment]
The more I think about it, LD is defined in Config{}, and we're already overriding it.

So the question becomes - what are we trying to accomplish? What flexibility do we prefer?
Do we want to be able to simply turn off your "special" values? If so, then we just add two options: --use-config-ld and --use-config-lddflags that will permit the user to use their Perl's ld/lddflags (and probably fail). 

Or, do we want them to be able to further specify/refine different ld/lddflags values that might match their existing Config{} values? Then we could add options for: --use-custom-ld and --use-custom-lddflags. This would give precedence to what was passed on the commandline over your special values.

We could actually do both, and then we just have to work out what to do if they are in conflict. Probably just die and alert the user.

**Comment by fsbruva** [comment]
@chincheta0815 
I am getting ready to begin a new round of testing, and am wondering if you have any other suggested changes based on your testing. Can you please merge this PR?

**Comment by chincheta0815** [comment]
Before you merge, please wait until I got the package created and sent to you via a merge request. I also patched NetSSL in my build due to changes in OpenSSL (there was a function deprecated making NetSSL refuse to compile.) I try to do that today evening.

**Comment by fsbruva** [comment]
@chincheta0815 
You merged this into you libmediascan repository, but it didn't make it into the libmediascan-0.3 tarball inside the slimserver-vendor PR you submitted.... What git commit corresponds to the files you used when creating the libmediascan-0.3 tarball?

**Comment by chincheta0815** [comment]
Sorry. Probably something went wrong when creating the tarball. It should have been the latest commit in the branch patches. If it's okay I will correct that on the weekend (planned saturday morning UTC).

**Comment by fsbruva** [comment]
No problem :-)
I was worried that mine wasn't the only one that got missed.

**Comment by chincheta0815** [comment]
Should work now.
I added the correct libmediascan-0.3 (hopefully).
There should now be your patch included plus an automatic check for my Illumos linker stuff.
Hope it works now.

**Pull request merged**
